#!/bin/bash
#x=1 y=1
#declare -A arr=(
#[00]=1 [01]=2 [02]=3
#[10]=4 [11]=5 [12]=6
#[20]=7 [21]=8 [22]=9
#)
#while read -r; do
  #for (( i = 0; i < ${#REPLY}; i++ )) do
    #case ${REPLY:i:1} in
      #U) (( x = x > 0 ? x-1 : x )) ;;
      #D) (( x = x < 2 ? x+1 : x )) ;;
      #L) (( y = y > 0 ? y-1 : y )) ;;
      #R) (( y = y < 2 ? y+1 : y )) ;;
    #esac
  #done
  #echo ${arr[$x$y]}
#done

declare -A arr=(
[00]=  [10]=  [20]=1 [30]=  [40]=
[01]=  [11]=2 [21]=3 [31]=4 [41]=
[02]=5 [12]=6 [22]=7 [32]=8 [42]=9
[03]=  [13]=A [23]=B [33]=C [43]=
[04]=  [14]=  [24]=D [34]=  [44]= 
)
x=0 y=2
while read -r; do
  for (( i = 0; i < ${#REPLY}; i++ )) do
    case ${REPLY:i:1} in
      U) [[ ${arr[$x$((y-1))]} ]] && (( y-- )) ;;
      D) [[ ${arr[$x$((y+1))]} ]] && (( y++ )) ;;
      L) [[ ${arr[$((x-1))$y]} ]] && (( x-- )) ;;
      R) [[ ${arr[$((x+1))$y]} ]] && (( x++ )) ;;
    esac
  done
  echo ${arr[$x$y]}
done
